seed: 42

device: "cuda"

aug:
  random_crop: 
    padding: 4
  random_horizontal_flip: true
  color_jitter:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.4
    probability: 0.8
  random_grayscale: 
    probability: 0.2

dataloader:
  batch_size: 100
  num_workers: 16

moco:
  dim: 128
  queue_size: 5000
  momentum: 0.999
  tau: 0.07

optimizer:
  lr: 0.03
  momentum: 0.9
  weight_decay: 0.0001

train:
  num_epochs: 200
  save_interval: 10

post_train:
  num_epochs: 50
  optimizer:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
